<?php

/**
 * @file
 * This is the module to create a drop-down menu for the core toolbar.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Render\Element;

/**
 * Implements hook_node_access().

function feature_cards_node_access(\Drupal\node\NodeInterface $node, $op, $account, $langcode) {
  // Ignore non-FAQ node.
  if ($node->getType() !== 'feature_page') {
    return AccessResult::neutral();
  }

  if ($op == 'view') {
    return AccessResult::neutral();
  }
  elseif ($op == 'create' || $op == 'update' || $op == 'delete') {
    if(\Drupal::currentUser()->hasPermission('administer Feature Page')) {
      return AccessResult::allowed();
    }
  }

  return AccessResult::neutral();
}
*/
/**
 * Implements hook_theme().
 */
function feature_cards_theme() {
  return array(
    'feature_cards_page' => array(
      'variables' => array('content' => '', 'cards' => '', 'description' => NULL),
      'template' => 'feature-cards-page',
    ),
  );
}

/**
 * Implements template_preprocess_page().
 *
 * Overrider breadcrumbs for faq pages.
 */
function feature_cards_preprocess_node(&$variables){
  if($variables['node']->getType() == "fc_feature_page"){
    if($variables['view_mode'] == 'full') {
      $variables['fcfp_menu'] = node_view($variables['node'], 'fcfp_menu');
      $variables['fcfp_intro'] = node_view($variables['node'], 'fcfp_intro');
      $variables['attributes']['id'] = 'fullpage';
      $variables['attributes']['role'] = 'main';
      //$variables['elements']['#attached']['library'][] = 'feature_cards/fcfp_fullPage';
    }
    elseif ($variables['view_mode'] == 'fcfp_menu') {
      $variables['attributes']['id'] = 'menu';
      unset($variables['attributes']['role']);
    }
  }
}

function feature_cards_page_attachments(array &$attachments) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if($node != null && $node->getType()) {
    $attachments['#attached']['library'][] = 'feature_cards/fcfp_fullPage';
  }
}


function feature_cards_preprocess_paragraph(&$variables) {
  if($variables['view_mode'] == 'default') {
    $anchor = $variables['paragraph']->get('fcfc_menu_title')->getValue();
    $variables['attributes']['anchor'] = $anchor[0]['value'];
    $variables['attributes']['class'][] = 'section';
  }
}

function feature_cards_preprocess_field(&$variables) {
  if($variables['field_name'] == 'fcfc_menu_title') {
    $vals = $variables['element']['#items']->getValue();
    $variables['content_attributes']['data-menuanchor'] = $vals[0]['value'];
    foreach($variables['items'] as $key => &$item) {
      $item['attributes']->setAttribute('href', '#' . $vals[$key]['value']);
    }
  }
}

/**
 * Implements hook_theme_registry_alter
 *
 * Register custom templates for this module's content types, paragraph types, and display modes.
 */
function feature_cards_theme_registry_alter(&$theme_registry) {
  // @TODO seems like there should be a better way to do this.
  $theme_registry['page__node__fc_feature_page'] = $theme_registry['page'];
  $theme_registry['page__node__fc_feature_page']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['page__node__fc_feature_page']['template'] = 'page--node--fc-feature-page';

  $theme_registry['node__fc_feature_page'] = $theme_registry['node'];
  $theme_registry['node__fc_feature_page']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['node__fc_feature_page']['template'] = 'node--fc-feature-page';

  $theme_registry['node__fc_feature_page__fcfp_menu'] = $theme_registry['node'];
  $theme_registry['node__fc_feature_page__fcfp_menu']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['node__fc_feature_page__fcfp_menu']['template'] = 'node--fc-feature-page--fcfp-menu';

  $theme_registry['paragraph__fc_feature_card'] = $theme_registry['paragraph'];
  $theme_registry['paragraph__fc_feature_card']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['paragraph__fc_feature_card']['template'] = 'paragraph--fc-feature-card';

  $theme_registry['paragraph__fc_feature_card__fcfc_menu_item'] = $theme_registry['paragraph'];
  $theme_registry['paragraph__fc_feature_card__fcfc_menu_item']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['paragraph__fc_feature_card__fcfc_menu_item']['template'] = 'paragraph--fc-feature-card--fcfc-menu-item';

  $theme_registry['field__fcfc_menu_title'] = $theme_registry['field'];
  $theme_registry['field__fcfc_menu_title']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['field__fcfc_menu_title']['template'] = 'field--fcfc-menu-title';

  $theme_registry['field__fcfp_feature_cards'] = $theme_registry['field'];
  $theme_registry['field__fcfp_feature_cards']['path'] = drupal_get_path('module', 'feature_cards') . '/templates';
  $theme_registry['field__fcfp_feature_cards']['template'] = 'field--fcfp-feature-cards';
}

function feature_cards_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Add content type suggestions.
  if ($node = \Drupal::request()->attributes->get('node')) {
    array_splice($suggestions, 1, 0, 'page__node__' . $node->getType());
  }
}